---
title: Jarad Comingdeer
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
email: jarad@jcomingdeer.com
description: 'I am a front-end web developer based in San Diego, California. I love
  building web applications.

'
baseurl: 
url: http://jaradcomingdeer.com
twitter_username: thebrownsound
github_username: thebrownsound
markdown: kramdown
